module ApiTypes

type Searcher =
  { Id: string
    Name: string
    Hint: string option
    Tooltip: string option
  }

[<RequireQualifiedAccess>]
type AttributeType =
  | None
  | FromId
  | ToId
  | Address
  | Album
  | AlexaRank
  | AlternateName
  | Annotator1Imageuri
  | Apn
  | AreaCode
  | Bio
  | Biography
  | Birthday
  | Brand
  | BvdId
  | CallSign
  | Cancelled
  | Caption
  | Category
  | Charges
  | City
  | Closed
  | Collectionid
  | Colour
  | CommentCount
  | Comments
  | CompaniesHouseId
  | CompanyNumber
  | CompanySize
  | Compliance
  | Confidence
  | Connections
  | Content
  | ContributorsEnabled
  | Coordinates
  | CorrectedNumber
  | Count
  | Country
  | CountryCode
  | CreatedAt
  | CreatedDate
  | CreatedTime
  | Data
  | Date
  | DateOfDeath
  | DateOfIssue
  | Deactivated
  | Description
  | DescriptionText
  | Digits
  | Direction
  | Disqualifications
  | Dob
  | DocumentId
  | DocumentNumber
  | DocumentType
  | Domain
  | DomainName
  | Duns
  | Education
  | EmailAddress
  | EmailAddresses
  | Encoding
  | EndTime
  | FamilyMembers
  | Favorited
  | FavouritesCount
  | FilingNumber
  | FirstName
  | FollowersCount
  | FollowingCount
  | Format
  | FormattedNumber
  | FriendCount
  | FullAddress
  | FullUrl
  | Gender
  | GeoEnabled
  | Groups
  | Hashtags
  | HeartsCount
  | HomeTown
  | Html
  | Id
  | Image
  | Imageuri
  | Imei
  | ImoNumber
  | IncorporationDate
  | Industry
  | InsolvencyHistory
  | Interests
  | IpAddress
  | IsCompany
  | JobTitle
  | Kind
  | Language
  | Languages
  | LastName
  | LastSeen
  | LikeCount
  | Liquidated
  | ListedCount
  | LiveListing
  | Locale
  | LocalName
  | LocalNumber
  | LocalPart
  | Location
  | Make
  | Members
  | MetaDescription
  | MetaKeywords
  | Model
  | Name
  | Nationality
  | NationalNumber
  | Network
  | Number
  | NumberOfShares
  | OccrpId
  | Occupation
  | OcId
  | OfficerNumber
  | OffshoreId
  | OriginalData
  | OtherAccounts
  | OtherNames
  | PageTitle
  | PhoneNumbers
  | Place
  | PlaceOfIssue
  | PossiblySensitive
  | Postcode
  | PostsCount
  | Price
  | PrimaryColour
  | Private
  | ProfileUrl
  | ReactCount
  | Region
  | Registration
  | RegistrationCountry
  | RegistrationState
  | RelationshipStatus
  | ReplyToName
  | ReplyToTweetId
  | Retweet
  | RetweetCount
  | RetweetId
  | RetweetUsername
  | ReviewStatus
  | ReviewTime
  | Salutation
  | SavedAt
  | ScreenName
  | SerialNumber
  | ShareCount
  | ShortDomain
  | SicCode
  | Site
  | Source
  | Ssn
  | StartTime
  | Status
  | StatusSince
  | Street1
  | Street2
  | Street3
  | Summary
  | TagLine
  | Tags'
  | Text
  | TextSize
  | Timestamp
  | TimeZone
  | Title
  | TloxpId
  | TotalOfficerships
  | TradeDescription
  | TweetsCount
  | Type
  | UpdatedAt
  | UpdatedTime
  | Uri
  | Url
  | Urls
  | Userid
  | UserId
  | UserMentions
  | Username
  | UserName
  | UtcOffset
  | VatNumber
  | Verified
  | VideosCount
  | Vin
  | Websites
  | Work
  | WorldCheckId
  | Worldcompliance
  | Year

[<RequireQualifiedAccess>]
type EntityType =
  | None
  | EntityGenericOnlineProfile
  | EntityAddress
  | EntityAsset
  | EntityBusiness
  | EntityCar
  | EntityCollege
  | EntityDarkWebPage
  | EntityDirectorRecord
  | EntityDocument
  | EntityDomain
  | EntityEbayProfile
  | EntityEmail
  | EntityEvent
  | EntityFacebookEvent
  | EntityFacebookGroup
  | EntityFacebookListing
  | EntityFacebookPage
  | EntityFacebookPhoto
  | EntityFacebookPost
  | EntityFacebookProfile
  | EntityFacebookVideo
  | EntityFlickrGroup
  | EntityFlickrProfile
  | EntityGabGroup
  | EntityGabPost
  | EntityGabProfile
  | EntityGooglePlusProfile
  | EntityGroup
  | EntityIdentityDocument
  | EntityImage
  | EntityImeiDevice
  | EntityInstagramLocation
  | EntityInstagramPost
  | EntityInstagramProfile
  | EntityIpAddress
  | EntityJustgivingProfile
  | EntityLabel
  | EntityLinkedinGroup
  | EntityLinkedinOrganisation
  | EntityLinkedinProfile
  | EntityMailServer
  | EntityNameServer
  | EntityNote
  | EntityOdnoklassnikiProfile
  | EntityOfficerRecord
  | EntityOnlineIdentity
  | EntityOrganisation
  | EntityParlerPost
  | EntityParlerProfile
  | EntityPerson
  | EntityPhoneNumber
  | EntityPhrase
  | EntityPinterestProfile
  | EntityPlane
  | EntityPosting
  | EntityProduct
  | EntityShip
  | EntitySoundcloudProfile
  | EntityTiktokProfile
  | EntityTripadvisorProfile
  | EntityTweet
  | EntityTwitterProfile
  | EntityUrlInfo
  | EntityVkontakteCommunity
  | EntityVkontaktePost
  | EntityVkontakteProfile
  | EntityWebPage
  | EntityWikipediaArticle
  | EntityWikipediaProfile
  | EntityYoutubeProfile
  | EntityYoutubeVideo
  | RelationshipAction
  | RelationshipAlias
  | RelationshipAttended
  | RelationshipContactDetail
  | RelationshipEmployedAt
  | RelationshipFamilyMember
  | RelationshipHas
  | RelationshipHosted
  | RelationshipIdentical
  | RelationshipInOnlineGroup
  | RelationshipLinksTo
  | RelationshipLocation
  | RelationshipMet
  | RelationshipNameserver
  | RelationshipNotSimilar
  | RelationshipOfficership
  | RelationshipOnlineAlsoViewed
  | RelationshipOnlineCommented
  | RelationshipOnlineEndorsement
  | RelationshipOnlineFollows
  | RelationshipOnlineFriends
  | RelationshipOnlineLikes
  | RelationshipOnlinePosted
  | RelationshipOnlineProfile
  | RelationshipOnlineProfileImage
  | RelationshipOnlineRecommendation
  | RelationshipOnlineShares
  | RelationshipOnlineTagged
  | RelationshipOwns
  | RelationshipPhoneCall
  | RelationshipRegistrant
  | RelationshipRelationship
  | RelationshipShareholding
  | RelationshipSimilar
  | RelationshipSourceLink
  | SourceHtmlDocument
  | SourceHtmlLog
  | SourceJsonDocument
  | SourceRdfDocument
  | SourceSource
  | SourceTextFile
  | SourceXmlDocument

type OutputEntity =
  { Type: EntityType
    Id: string
    Attributes: Map<AttributeType,string> // we're collecting everything as strings which might not be appropriate
  }

type SearchResult =
  { Key: string
    Title: string option
    Subtitle: string option
    Url: string option
    Summary: string option
    Source: string option
    Entities: (OutputEntity list) option
  }

type SearchResultSet =
  { SearchResults: SearchResult list }



