searchers:
  grid_company:
    id: grid_company
    name: Moody's GRID - Companies
    hint: Search by name
    tooltip: Moody's GRID company search
    enabled: True
  grid_people:
    id: grid_people
    name: Moody's GRID - People
    hint: Search by name
    tooltip: Moody's GRID person search
    enabled: True
