searchers:
  littlesis:
    id: littlesis
    name: Little Sis
    hint: Search for a person
    tooltip: Find Gravatar profile by email address
    enabled: True # True or False
  gravatar:
    id: gravatar
    name: Gravatar
    hint: Search by email address
    tooltip: Find Gravatar profile by email address
    enabled: True # True or False
  bitcoin:
    id: bitcoin
    name: BitCoin Abuse
    hint: Check for abused BitCoin wallets
    tooltip: Search by BitCoin wallet address
    enabled: True # True or False
    redirect: http://90.220.172.4:3010/searchers/Videris124/results