searchers:
  cribis_company:
    id: cribis_company
    name: CRIBIS Companies
    hint: Enter a company to search for
    tooltip: Get the CRIBIS information of a company
    enabled: True
  cribis_people:
    id: cribis_people
    name: CRIBIS People
    hint: Enter a person to search for
    tooltip: Get the CRIBIS information of a person
    enabled: True
